### ISSUE TITLE
Erro no check_env

### ISSUE THREAD

**Issue by Silop** [ocefpaf/2016-Python-course-CBO#3]
Bom dia, 
No fim da instalação, quando vou conferir todos os pacotes e instalções pelo kernel, o check_env fica rodando muito tempo com a mensagem "running" no home, e dentro do próprio check_env não há erros, claro que como está rodando nem todas as células retornam as saídas. Isso é normal? Quando fizeram os testes quanto tempo demorou esse proceso? 
Obrigado pela ajuda.

**Comment by ocefpaf** [comment]
>  Quando fizeram os testes quanto tempo demorou esse processo?

Os testes não devem demorar (< 3 min) muito mas isso varia bastante dependendo da configuração. Você está usando Windows, Linux ou Mac?

> claro que como está rodando nem todas as células retornam as saídas

Em qual célula o processo "para" e fica sem resposta? As repostas das outras células estão OK ou apresentam algum erro?

**Comment by Silop** [comment]
Eu uso Linux. 
Nenhuma célula até o momento retorna erro, e o processo não para, é como se pulasse algumas células e continuasse a rodar. As que não tem saída são: 11, 25, 28 não retornam nenhuma mensagem. 12 à 19, 21 à 24, 31 e 32 tem uma saída porém sem a campo OUT na coluna ao lado.

**Comment by ocefpaf** [comment]
> Eu uso Linux. 

:+1: 

> Nenhuma célula até o momento retorna erro, e o processo não para, é como se pulasse algumas células e continuasse a rodar.

Isso é normal. Depende do que a célula está fazendo.

> As que não tem saída são: 11, 25, 28 não retornam nenhuma mensagem.

Essas apenas "importam" módulos que utilizaremos no curso. Como não retorna erro está OK.

> 12 à 19, 21 à 24

Como termino a célula como `print` você tem que ver a versão sendo "printed" abaixo da célula. A ausência do `Out [x]` não é um problema.

> , 31 e 32 tem uma saída porém sem a campo OUT na coluna ao lado. 

A saída dessa duas são figuras. Você consegue vê-las?

**Comment by Silop** [comment]
Sim vejo as imagens em 31 e 32 . Os módulos printed retornam as versões sim, achei estranho que os módulos iniciais também importam e retornam abaixo da célula e como o processo não para no meu terminal achei que estavam ainda estavam rodando. A última linha do meu terminal está assim: 
 [I 10:15:07.133 NotebookApp] Saving file at /check_env.ipynb ... e não consigo terminar o processo apenas fechando o check_env manualmente no navegador.

**Comment by ocefpaf** [comment]
> Sim vejo as imagens em 31 e 32.

:+1: 

> Os módulos printed retornam as versões sim, achei estranho que os módulos iniciais também importam e retornam abaixo da célula e como o processo não para no meu terminal achei que estavam ainda estavam rodando.

Isso é normal.

> A última linha do meu terminal está assim: 
>  [I 10:15:07.133 NotebookApp] Saving file at /check_env.ipynb ... e não consigo terminar o processo apenas fechando o check_env manualmente no navegador.

Isso também é normal. Vou colocar uma nota nas instruções para ajudar a entender o que está acontecendo lá. Obrigado @Silop!

**Comment by Silop** [comment]
Obrigado @ocefpaf  , me desculpe pelo incomodo, já que tudo estava certo e eu só não entendi.

**Comment by ocefpaf** [comment]
> Obrigado @ocefpaf  , me desculpe pelo incomodo, já que tudo estava certo e eu só não entendi. 

Não é incômodo algum. Quanto mais cedo resolvermos dúvidas de instalação melhor será a experiência no dia do curso.
